version: 1
accounts:
- name: validator0
  coins:
  - 210000000000uhby
  - 200000000000ushby
- name: validator1
  coins:
  - 210000000000uhby
  - 200000000000ushby
- name: validator2
  coins:
  - 210000000000uhby
  - 200000000000ushby
- name: validator3
  coins:
  - 210000000000uhby
  - 200000000000ushby
- name: validator4
  coins:
  - 210000000000uhby
  - 200000000000ushby
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: validator0
  bonded: 200000000000uhby
  home: "/data/node0"
  ip: "172.20.0.100"
  app:
    minimum-gas-prices: "0.000002ushby,0.000002uhby"
    api:
      enable: true
      enabled-unsafe-cors: true
      address: "tcp://0.0.0.0:1317"
    grpc:
      enable: true
      address: "0.0.0.0:9090"
    grpc-web:
      address: "0.0.0.0:9091"
      enable: true
      enable-unsafe-cors: true
  config:
    consensus:
      timeout_commit: "5s"
    proxy_app: "tcp://0.0.0.0:26658"
    moniker: "node0"
    rpc:
      max_body_bytes: "10240000"
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
      persistent_peers: ""
      allow_duplicate_ip: true
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
- name: validator1
  bonded: 200000000000uhby
  home: "/data/node1"
  ip: "172.20.0.101"
  app:
    minimum-gas-prices: "0.000002ushby,0.000002uhby"
    api:
      enable: true
      enabled-unsafe-cors: true
      address: "tcp://0.0.0.0:1317"
    grpc:
      enable: true
      address: "0.0.0.0:9090"
    grpc-web:
      address: "0.0.0.0:9091"
      enable: true
      enable-unsafe-cors: true
  config:
    consensus:
      timeout_commit: "5s"
    proxy_app: "tcp://0.0.0.0:26658"
    moniker: "node1"
    rpc:
      max_body_bytes: "10240000"
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
      persistent_peers: ""
      allow_duplicate_ip: true
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
- name: validator2
  bonded: 200000000000uhby
  home: "/data/node2"
  ip: "172.20.0.102"
  app:
    minimum-gas-prices: "0.000002ushby,0.000002uhby"
    api:
      enable: true
      enabled-unsafe-cors: true
      address: "tcp://0.0.0.0:1317"
    grpc:
      enable: true
      address: "0.0.0.0:9090"
    grpc-web:
      address: "0.0.0.0:9091"
      enable: true
      enable-unsafe-cors: true
  config:
    consensus:
      timeout_commit: "5s"
    proxy_app: "tcp://0.0.0.0:26658"
    moniker: "node2"
    rpc:
      max_body_bytes: "10240000"
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
      persistent_peers: ""
      allow_duplicate_ip: true
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
- name: validator3
  bonded: 200000000000uhby
  home: "/data/node3"
  ip: "172.20.0.103"
  app:
    minimum-gas-prices: "0.000002ushby,0.000002uhby"
    api:
      enable: true
      enabled-unsafe-cors: true
      address: "tcp://0.0.0.0:1317"
    grpc:
      enable: true
      address: "0.0.0.0:9090"
    grpc-web:
      address: "0.0.0.0:9091"
      enable: true
      enable-unsafe-cors: true
  config:
    consensus:
      timeout_commit: "5s"
    proxy_app: "tcp://0.0.0.0:26658"
    moniker: "node3"
    rpc:
      max_body_bytes: "10240000"
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
      persistent_peers: ""
      allow_duplicate_ip: true
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
- name: validator4
  bonded: 200000000000uhby
  home: "/data/node4"
  ip: "172.20.0.104"
  app:
    minimum-gas-prices: "0.000002ushby,0.000002uhby"
    api:
      enable: true
      enabled-unsafe-cors: true
      address: "tcp://0.0.0.0:1317"
    grpc:
      enable: true
      address: "0.0.0.0:9090"
    grpc-web:
      address: "0.0.0.0:9091"
      enable: true
      enable-unsafe-cors: true
  config:
    consensus:
      timeout_commit: "5s"
    proxy_app: "tcp://0.0.0.0:26658"
    moniker: "node4"
    rpc:
      max_body_bytes: "10240000"
      laddr: "tcp://0.0.0.0:26657"
    p2p:
      laddr: "tcp://0.0.0.0:26656"
      persistent_peers: ""
      allow_duplicate_ip: true
    instrumentation:
      prometheus: true
      prometheus_listen_addr: ":26660"
genesis:
  chain_id: "coeus"
  initial_height: "1"
  genesis_time: "2023-11-09T07:46:56.293077949Z"
  consensus_params:
    block:
      max_gas: "1000000000"
    version:
      app: "9160"
  app_state:
    bank:
      denom_metadata:
        - description: "The native staking token"
          base: "uhby"
          display: "hby"
          name: "staking token"
          symbol: "HBY"
          uri: ""
          denom_units:
            - aliases: [ ]
              denom: "uhby"
              exponent: 0
            - aliases: [ ]
              denom: "hby"
              exponent: 6
        - description: "The native gov token"
          base: "ushby"
          display: "shby"
          name: "mint token"
          symbol: "SHBY"
          uri: ""
          denom_units:
            - aliases: [ ]
              denom: "ushby"
              exponent: 0
            - aliases: [ ]
              denom: "shby"
              exponent: 6
    staking:
      params:
        bond_denom: "uhby"
        max_validators: "500"
    mint:
      minter:
        annual_provisions: "0.000000000000000000"
        inflation: "0.000000000000000000"
      params:
        mint_denom: "ushby"
        blocks_per_year: "4505142"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.200000000000000000"
        inflation_min: "0.070000000000000000"
        inflation_rate_change: "0.130000000000000000"
        reduction:
          enable: true
          total_provisions: "500000000000000"
          heights: [ 9010284,18020568,27030852,36041136,45051420 ]
    gov:
      params:
        min_deposit:
          - amount: "10000000000"
            denom: "ushby"
    distribution:
      params:
        base_proposer_reward: "0.010000000000000000"
        bonus_proposer_reward: "0.040000000000000000"
        community_tax: "0.020000000000000000"
        withdraw_addr_enabled: true
    crisis:
      constant_fee:
        amount: "10000000000"
        denom: "ushby"
